fix: install RGB to YUV in oldstable

diff --git a/src/extensions/gd/Dockerfile b/src/extensions/gd/Dockerfile
--- a/src/extensions/gd/Dockerfile
+++ b/src/extensions/gd/Dockerfile
@@ -9,6 +9,11 @@ RUN apt-get update && apt-get install -y \
     libgmp-dev \
     libwebp-dev \
     libfreetype6-dev \
+    lsb-release
+
+RUN if [ "$(lsb_release -sc)" = "bookworm" ]; then echo "deb http://deb.debian.org/debian bookworm-backports main" > /etc/apt/sources.list.d/bookworm-backports.list; apt-get update && apt-get install -y -t bookworm-backports libsharpyuv0; \
+    else apt-get install -y libsharpyuv0; \
+    fi \
     && apt-get clean
 
 # Configure and install GMP
@@ -31,6 +36,8 @@ RUN mkdir -p /tmp/lib64 && \
   [ -f /tmp/lib64/libjpeg.so.62 ] || { echo "Error: libjpeg.so.62 is missing"; exit 1; } && \
   find /usr/lib -name libfreetype.so.6 -exec cp {} /tmp/lib64/ \; && \
   [ -f /tmp/lib64/libfreetype.so.6 ] || { echo "Error: libfreetype.so.6 is missing"; exit 1; } && \
+  find /usr/lib -name libgmp.so.10 -exec cp {} /tmp/lib64/ \; && \
+  [ -f /tmp/lib64/libgmp.so.10 ] || { echo "Error: libgmp.so.10 is missing"; exit 1; } && \
   find /usr/lib \( -name libwebp.so.7 -o -name libwebp.so.6 \) -exec cp {} /tmp/lib64/ \; && \
   ( [ -f /tmp/lib64/libwebp.so.7 ] || [ -f /tmp/lib64/libwebp.so.6 ] ) || { echo "Error: libwebp.so.* is missing"; exit 1; } && \
   find /usr/lib -name libsharpyuv.so.0 -exec cp {} /tmp/lib64/ \; && \
