fix: only push gd when files are actually there

diff --git a/src/extensions/gd/Dockerfile b/src/extensions/gd/Dockerfile
--- a/src/extensions/gd/Dockerfile
+++ b/src/extensions/gd/Dockerfile
@@ -24,12 +24,17 @@ RUN mv `php-config --extension-dir`/gd.so /tmp/extensions/gd.so \
   && echo "extension=/opt/php/extensions/gd.so" >> /tmp/conf.d/ext-gd.ini
 
 USER root
-RUN mkdir -p /tmp/lib64 \
-  && cp `find /usr/lib -name libpng16.so.16` /tmp/lib64/ \
-  && cp `find /usr/lib -name libjpeg.so.62` /tmp/lib64/ \
-  && cp `find /usr/lib -name libfreetype.so.6` /tmp/lib64/ \
-  && cp `find /usr/lib \( -name libwebp.so.7 -o -name libwebp.so.6 \)` /tmp/lib64/ \
-  && cp `find /usr/lib -name libsharpyuv.so.0` /tmp/lib64/
+RUN mkdir -p /tmp/lib64 && \
+  find /usr/lib -name libpng16.so.16 -exec cp {} /tmp/lib64/ \; && \
+  [ -f /tmp/lib64/libpng16.so.16 ] || { echo "Error: libpng16.so.16 is missing"; exit 1; } && \
+  find /usr/lib -name libjpeg.so.62 -exec cp {} /tmp/lib64/ \; && \
+  [ -f /tmp/lib64/libjpeg.so.62 ] || { echo "Error: libjpeg.so.62 is missing"; exit 1; } && \
+  find /usr/lib -name libfreetype.so.6 -exec cp {} /tmp/lib64/ \; && \
+  [ -f /tmp/lib64/libfreetype.so.6 ] || { echo "Error: libfreetype.so.6 is missing"; exit 1; } && \
+  find /usr/lib \( -name libwebp.so.7 -o -name libwebp.so.6 \) -exec cp {} /tmp/lib64/ \; && \
+  ( [ -f /tmp/lib64/libwebp.so.7 ] || [ -f /tmp/lib64/libwebp.so.6 ] ) || { echo "Error: libwebp.so is missing"; exit 1; } && \
+  find /usr/lib -name libsharpyuv.so.0 -exec cp {} /tmp/lib64/ \; && \
+  [ -f /tmp/lib64/libsharpyuv.so.0 ] || { echo "Error: libsharpyuv.so.0 is missing"; exit 1; }
 
 FROM scratch
 COPY --from=ext /tmp/extensions/ /opt/php/extensions/
